kind: PersistentVolume
apiVersion: v1
metadata:
  labels:
    openstack-app: neutron-db
  name: os-neutron-db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/harbor/neutron/mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    openstack-app: neutron-db
  name: os-neutron-db
  namespace: os-neutron
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: neutron-manager
    version: v0.1.0
  name: neutron-manager
  namespace: os-neutron
spec:
  template:
    metadata:
      labels:
        openstack-app: neutron-manager
        version: v0.1.0
      name: neutron-manager
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-manager
          image: {{ IMAGE_NEUTRON_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-kubecfg
              mountPath: /var/run/harbor/secrets/config-kubecfg
              readOnly: true
            - name: os-config-user-ipa
              mountPath: /var/run/harbor/secrets/config-user-ipa
              readOnly: true
            - name: os-config-host-ipa
              mountPath: /var/run/harbor/secrets/config-host-ipa
              readOnly: true
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
            - name: os-config-keystone-admin-user
              mountPath: /var/run/harbor/secrets/config-keystone-admin-user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-kubecfg
          secret:
            secretName: neutron-kubecfg
        - name: os-config-user-ipa
          secret:
            secretName: neutron-user-ipa
        - name: os-config-host-ipa
          secret:
            secretName: neutron-host-ipa
        - name: os-config-db-root
          secret:
            secretName: neutron-db-root
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-secret
          secret:
            secretName: neutron-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
        - name: os-config-keystone-admin-user
          secret:
            secretName: keystone-admin-user
---
apiVersion: extensions/v1beta1
kind: Job
metadata:
  labels:
    openstack-app: neutron-manager
    version: v0.1.0
  name: neutron-manager
  namespace: os-neutron
spec:
  template:
    metadata:
      labels:
        openstack-app: neutron-manager
        version: v0.1.0
      name: neutron-manager
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-manager
          image: {{ IMAGE_NEUTRON_MANAGER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: OS_MANAGEMENT_ACTION
              value: bootstrap
          volumeMounts:
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      restartPolicy: OnFailure
      volumes:
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: neutron-db
    version: v0.1.0
  name: neutron-db
  namespace: os-neutron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: neutron-db
        version: v0.1.0
      name: neutron-db
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-db
          image: {{ IMAGE_MARIADB_SERVER }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 3308
              hostPort: 3308
              protocol: TCP
              name: mysql
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
            - name: DB_PORT
              value: '3308'
            - name: DB_TLS
              value: /run/harbor/auth/db
            - name: DB_ROOT_PASSWORD
              value: AUTH_NEUTRON_DB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              value: AUTH_NEUTRON_MARIADB_DATABASE
            - name: MARIADB_USER
              value: AUTH_NEUTRON_MARIADB_USER
            - name: MARIADB_PASSWORD
              value: AUTH_NEUTRON_MARIADB_PASSWORD
            - name: DB_NAME
              value: AUTH_NEUTRON_DB_NAME
            - name: DB_USER
              value: AUTH_NEUTRON_DB_USER
            - name: DB_PASSWORD
              value: AUTH_NEUTRON_DB_PASSWORD
          volumeMounts:
            - name: os-config-db-root
              mountPath: /var/run/harbor/secrets/config-db-root
              readOnly: true
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-db-ssl-secret
              mountPath: /run/harbor/auth/db
              readOnly: true
            - mountPath: /var/lib/mysql
              name: os-neutron-db
              readOnly: false
      volumes:
        - name: os-config-db-root
          secret:
            secretName: neutron-db-root
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-db-ssl-secret
          secret:
            secretName: neutron-db-ssl-secret
        - name: os-neutron-db
          persistentVolumeClaim:
            claimName: os-neutron-db
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: neutron
    version: v0.1.0
  name: neutron-api-master
  namespace: os-neutron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: neutron
        version: v0.1.0
      name: neutron-api-master
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-api
          image: {{ IMAGE_NEUTRON_API }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          ports:
            - containerPort: 9696
              hostPort: 9696
              protocol: TCP
              name: q-api
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-secret
              mountPath: /run/harbor/auth/ssl
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: false
      volumes:
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-secret
          secret:
            secretName: neutron-ssl-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: neutron-metadata
    version: v0.1.0
  name: neutron-metadata-master
  namespace: os-neutron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: neutron-metadata
        version: v0.1.0
      name: neutron-metadata-master
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-metadata
          image: {{ IMAGE_NEUTRON_METADATA_AGENT }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: host-var-run-openvswitch
              mountPath: /var/run/openvswitch
              readOnly: false
            - name: host-dev
              mountPath: /dev
              readOnly: false
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-neutron-shared-secret
              mountPath: /var/run/harbor/secrets/config-neutron-shared-secret
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: host-var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: host-dev
          hostPath:
            path: /dev
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-neutron-shared-secret
          secret:
            secretName: neutron-shared-secret
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: neutron-lbaas
    version: v0.1.0
  name: neutron-lbaas-master
  namespace: os-neutron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: neutron-lbaas
        version: v0.1.0
      name: neutron-lbaas-master
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neutron-lbaas-agent
          image: {{ IMAGE_NEUTRON_LBAAS_AGENT }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: host-var-run-openvswitch
              mountPath: /var/run/openvswitch
              readOnly: false
            - name: host-dev
              mountPath: /dev
              readOnly: false
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: host-var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: host-dev
          hostPath:
            path: /dev
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    openstack-app: neutron-l3
    version: v0.1.0
  name: neutron-l3-master
  namespace: os-neutron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        openstack-app: neutron-l3
        version: v0.1.0
      name: neuton-l3-master
      namespace: os-neutron
    spec:
      hostNetwork: true
      nodeSelector:
        harbor-role: master
      containers:
        - name: neuton-l3-agent
          image: {{ IMAGE_NEUTRON_L3_AGENT }}
          imagePullPolicy: {{ IMAGE_PULL_POLICY }}
          env:
            - name: OS_DOMAIN
              value: {{ OS_DOMAIN }}
          volumeMounts:
            - name: host-var-run-openvswitch
              mountPath: /var/run/openvswitch
              readOnly: false
            - name: host-dev
              mountPath: /dev
              readOnly: false
            - name: os-config-db
              mountPath: /var/run/harbor/secrets/config-db
              readOnly: true
            - name: os-config-keystone
              mountPath: /var/run/harbor/secrets/config-keystone
              readOnly: true
            - name: os-config-messaging-auth
              mountPath: /var/run/harbor/secrets/config-messaging-auth
              readOnly: true
            - name: os-config-ssl-user-secret
              mountPath: /run/harbor/auth/user
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: host-var-run-openvswitch
          hostPath:
            path: /var/run/openvswitch
        - name: host-dev
          hostPath:
            path: /dev
        - name: os-config-db
          secret:
            secretName: neutron-db
        - name: os-config-keystone
          secret:
            secretName: neutron-keystone
        - name: os-config-messaging-auth
          secret:
            secretName: messaging-auth
        - name: os-config-ssl-user-secret
          secret:
            secretName: neutron-user-ssl-secret
